export enum ListItem {
  顯示使用者姓名 = 'Common,UseInfo,Name',
  顯示使用者ID = 'Common,UseInfo,Account',
  顯示使用者ID_姓名 = 'Common,UseInfo,AccountName',
  顯示Site = 'Common,UseInfo,Site',
  顯示工號_中名_英名_Site = 'Common,UseInfo,SecretaryName',
  顯示角色名稱 = 'Common,UseRole,RoleName',
  顯示Location名稱 = 'Common,WfLocation,LocationName',
  顯示Location英文名稱 = 'Common,WfLocation,LocationEName',
  與Site關聯_顯示Location名稱 = 'Common,WfLocation,Site_LocationName',
  當前依使用者Zone_取得Location分區 = 'Common,WfLocation,LocationArea',
  顯示LocationCode_Location名稱 = 'Common,WfLocation,LocationIdName',
  依據_使用者_的Zone_顯示Site = 'Common,Wf_Zone_Site,Site',
  針對還沒使用過的Site_顯示Site = 'Common,Wf_Zone_Site,EnableSite',
  針對已經使用過的Site_顯示Site = 'Common,Wf_Zone_Site,DisenableSite',
}
